### ISSUE TITLE
Undefied textures after using the lastest Thorium

### ISSUE THREAD

**Issue by Scarlaid** [PotassiumMC/thorium#9] opened 2022-05-03 12:53 UTC
### Expected behavior

The same workout with older versions

### Observed/Actual behavior

Some blocks, mention here: **Crimson Stem**, **Prismarine**, **Magma Block**, **Warped Stem** lost their textures

### Steps/models to reproduce

- Use the lastest Thorium
- Go to creative mode
- Scrolling down **Building Blocks**

You should be able to see some of the blocks having no textures beside Purple/Black thing 

### Other

Left is without Thorium, right is with Thorium
Same issue without a texturepack
Older version did not have this issue whatsoever

Lastest log (left): [2022-05-03-7.log](https://github.com/PotassiumMC/thorium/files/8610513/2022-05-03-7.log)
Lastest log (right): [latest.log](https://github.com/PotassiumMC/thorium/files/8610507/latest.log)
![ok](https://user-images.githubusercontent.com/90851437/166455985-90deeefa-a940-4c47-b19b-8fa41bd9c87a.jpg)

**Comment by Scarlaid** [comment] 2022-05-03 12:57
> This should have been earlier but I was playing the game, as wasn't paying attention to the bug
> Hoping this isn't issue spam

**Comment by NoahvdAa** [comment] 2022-05-03 13:15
I'm having some trouble reproducing this. Could you send your full mod list (including version numbers)? The logs also contain libraries, making it a bit hard for me to see which mods are just included in other mods.

**Comment by Scarlaid** [comment] 2022-05-03 16:31
Below is my full mod folder, all are lastest, 1.18.2
If I also need to link a mod folder download just tell me

![image](https://user-images.githubusercontent.com/90851437/166497206-aad470c9-8aab-4744-a1c5-8bb2459a0cfa.png)

**Comment by NoahvdAa** [comment] 2022-05-03 16:47
That's a lot of mods 😅 
Could you (privately) send me a ZIP archive containing all of them? Downloading all 145 of them is going to take me way too long...

**Comment by Scarlaid** [comment] 2022-05-03 23:52
I could just send here because the modpack is already on my github but I haven't updated it
https://cdn.discordapp.com/attachments/788051866495090732/971197469587279952/mods.zip

**Comment by NoahvdAa** [comment] 2022-05-04 09:39
Can reproduce, narrowed it down to sodium, which is odd since I explicitly tested with it. Working on a fix.

**Comment by NoahvdAa** [comment] 2022-05-04 09:59
Fixed in c630214. A release will be out shortly.

**Closed by NoahvdAa** 2022-05-04 09:59 UTC
Labels: status: accepted, type: bug, type: incompatibility

**Comment by Scarlaid** [comment] 2022-05-04 14:41
The older version of Thorium works perfectly fine with Sodium
I'm merely confused, but thank you for the quick fix 🎉
